spring.application.name="OmniSync"

spring.devtools.restart.enabled=true

# segredo do JWT (mínimo 32 chars se for HS256/HS512; aqui vou usar HS256 com chave forte)
app.jwt.secret=coloca-uma-chave-grande-aqui-com-mais-de-32-caracteres
app.jwt.accessExpMinutes=1
app.jwt.refreshExpDays=7

# cookie
app.cookie.accessName=ACCESS_TOKEN
app.cookie.refreshName=REFRESH_TOKEN
app.cookie.secure=false

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=${DB_DRIVER:org.postgresql.Driver}

spring.jpa.hibernate.ddl-auto=validate
app.crypto.secret=superStrongEncryptionKey
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

mercadolivre.client-id=897819191598162
mercadolivre.client-secret=zBbphu12CNLSdfBLlcLU9TMJqDPau3em
mercadolivre.redirect-uri=${MELI_REDIRECT_URI:https://omnisync.site/home}
mercadolivre.oauth.state-secret=${MELI_STATE_SECRET:${app.crypto.secret}}
mercadolivre.oauth.state-ttl-seconds=${MELI_STATE_TTL_SECONDS:600}

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
